name: Build and Upload Distributable

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install SDL2 (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

      - name: Install SDL2 (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install sdl2 sdl2_ttf

      - name: Install SDL2 (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install sdl2 sdl2-ttf

      - name: Build native library
        # On macOS, Homebrew installs SDL2/SDL2_ttf headers and libraries in non-standard locations.
        # We pass these paths directly to CMake so it can find them reliably.
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            BREW_PREFIX=$(brew --prefix)
            cd native
            cmake . -DCMAKE_INCLUDE_PATH="$BREW_PREFIX/include" -DCMAKE_LIBRARY_PATH="$BREW_PREFIX/lib"
            cmake --build .
            cd ..
          else
            cd native
            cmake .
            cmake --build .
            cd ..
          fi

      - name: Build Dart executable
        run: |
          dart pub get
          mkdir -p build
          dart compile exe bin/john_gospel_game.dart -o build/john_gospel_game${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Prepare dist folder
        run: |
          mkdir -p dist/assets
          cp build/john_gospel_game* dist/ || true
          cp native/*.so dist/ 2>/dev/null || true
          cp native/*.dylib dist/ 2>/dev/null || true
          cp native/*.dll dist/ 2>/dev/null || true
          cp -r assets/* dist/assets/ || true

      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../dist-${{ github.ref_name }}-${{ matrix.os }}.zip .
        shell: bash

      - name: Upload to existing release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist-${{ github.ref_name }}-${{ matrix.os }}.zip
          asset_name: dist-${{ github.ref_name }}-${{ matrix.os }}.zip
          tag: ${{ github.ref_name }}
          overwrite: true
