name: Build and Upload Distributable (Ubuntu)

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

      - name: Build native library
        run: |
          cd native
          cmake .
          cmake --build .
          cd ..

      - name: Build Dart executable
        run: |
          dart pub get
          mkdir -p build
          dart compile exe bin/john_gospel_game.dart -o build/john_gospel_game

      - name: Prepare dist folder
        run: |
          mkdir -p dist/assets
          cp build/john_gospel_game* dist/ || true
          cp native/*.so dist/ 2>/dev/null || true
          cp -r assets/* dist/assets/ || true

      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../dist-${{ github.ref_name }}-ubuntu-latest.zip .
        shell: bash

      - name: Upload to existing release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist-${{ github.ref_name }}-ubuntu-latest.zip
          asset_name: dist-${{ github.ref_name }}-ubuntu-latest.zip
          tag: ${{ github.ref_name }}
          overwrite: true
